# Generated by Django 5.0.1 on 2024-05-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('listing', '0002_rename_user_customuser_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='user',
        ),
    ]
