# Generated by Django 5.0.1 on 2024-05-20 06:18

from django.db import migrations
from listing.managers import CustomUserManager

class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_transaction'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', CustomUserManager()),
            ],
        ),
    ]
