# Generated by Django 5.0.1 on 2024-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
