# Generated by Django 5.0.1 on 2024-05-22 09:36

from django.db import migrations
from listing.managers import CustomUserManager


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', CustomUserManager()),
            ],
        ),
    ]
