# Generated by Django 5.0.1 on 2024-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
