# Generated by Django 5.0.1 on 2024-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
